//! Built-in command table. Behaviour lives in the front-ends; this is
//! just the descriptor list. New commands across phases append here.

use super::registry::{CommandAction, SlashCommand};

pub static BUILTINS: &[SlashCommand] = &[
    SlashCommand {
        name: "help",
        description: "Show commands and keybindings",
        usage: "/help",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "clear",
        description: "Clear the conversation context",
        usage: "/clear",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "exit",
        description: "Quit zode",
        usage: "/exit",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "model",
        description: "Show or switch the active model",
        usage: "/model [id]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "vision",
        description: "Configure image understanding",
        usage: "/vision [mode|provider|model|prompt]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "config",
        description: "Print the effective config",
        usage: "/config",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "compact",
        description: "Summarize and compact the conversation",
        usage: "/compact",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "cost",
        description: "Show token usage and cost so far",
        usage: "/cost",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "currency",
        description: "Switch the display currency for cost (USD, CNY, EUR, …)",
        usage: "/currency [code]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "op",
        description: "Drive OpenPencil (e.g. /op status, /op generate <prompt>)",
        usage: "/op <status|design '<dsl>'|generate <prompt>|<tool> <json>>",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "browser",
        description: "Browser control panel and commands (e.g. /browser, /browser status)",
        usage: "/browser [status|launch|close|pair|target <managed|bridge>|screenshot [path]]",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "desktop",
        description: "Desktop control status and CDP attach (e.g. /desktop status)",
        usage: "/desktop [status|attach <port>]",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "team",
        description: "Show the agent team roster (e.g. /team, /team board, /team dismiss <name>)",
        usage: "/team [status|board|dismiss <name>]",
        action: CommandAction::Engine,
    },
    // Registered now, fully wired in later phases.
    SlashCommand {
        name: "theme",
        description: "Switch the TUI theme",
        usage: "/theme [id]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "sessions",
        description: "List and resume sessions",
        usage: "/sessions",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "tab",
        description: "Switch session tab",
        usage: "/tab [n|next|prev]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "connect",
        description: "Connect a provider",
        usage: "/connect",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "sidebar",
        description: "Show or hide the sidebar",
        usage: "/sidebar [on|off|toggle|auto|mcp|files|todo]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "resume",
        description: "Resume a session by id",
        usage: "/resume <id>",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "tasks",
        description: "Background shells + running turns",
        usage: "/tasks",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "undo",
        description: "Undo the last file edit",
        usage: "/undo",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "redo",
        description: "Redo the last undone edit",
        usage: "/redo",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "yolo",
        description: "Toggle bypass-approval mode",
        usage: "/yolo",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "sandbox",
        description: "Show / control the OS sandbox for shell commands",
        usage: "/sandbox [on|off|read-only|workspace-write|network on|network off]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "plan",
        description: "Toggle plan mode (read-only; research then present a plan)",
        usage: "/plan",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "mcp",
        description: "Manage MCP servers: enable / disable",
        usage: "/mcp",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "memory",
        description: "Manage Noema long-term memory",
        usage: "/memory [status|remember [project|user] <text>|search <query>|root]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "skills",
        description: "List available skills",
        usage: "/skills",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "plugin",
        description: "Manage plugins (tools, MCP, skills, LSP): list / toggle",
        usage: "/plugin [id]",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "goal",
        description: "Set/clear a persistent objective in the system prompt",
        usage: "/goal [text]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "effort",
        description: "Tune thoroughness: low | medium | high",
        usage: "/effort [low|medium|high]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "copy",
        description: "Copy the last response to the clipboard",
        usage: "/copy",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "export",
        description: "Export the conversation to a Markdown file",
        usage: "/export [path]",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "diff",
        description: "Show the working-tree git diff",
        usage: "/diff",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "agents",
        description: "Manage sub-agents: list / create / delete",
        usage: "/agents",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "external-agents",
        description: "Discover and register installed external agent CLIs",
        usage: "/external-agents [list|discover]",
        action: CommandAction::Local,
    },
    SlashCommand {
        name: "subagents",
        description: "Open the sub-agent activity panel",
        usage: "/subagents",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "permissions",
        description: "Show tool permission rules (allow / ask / deny)",
        usage: "/permissions",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "hooks",
        description: "List configured hooks",
        usage: "/hooks",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "reload-plugins",
        description: "Re-read plugin state and rebuild the active session",
        usage: "/reload-plugins",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "reload-skills",
        description: "Re-scan skills from disk and rebuild the active session",
        usage: "/reload-skills",
        action: CommandAction::Engine,
    },
    SlashCommand {
        name: "language",
        description: "Switch the UI language",
        usage: "/language",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "workflows",
        description: "Manage workflows: list / create / delete",
        usage: "/workflows",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "orchestration",
        description: "Toggle autonomous orchestration (auto sub-agents)",
        usage: "/orchestration",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "thinking",
        description: "Toggle showing the agent's thinking output",
        usage: "/thinking",
        action: CommandAction::Ui,
    },
    SlashCommand {
        name: "tool-details",
        description: "Toggle showing tool-call detail in the chat",
        usage: "/tool-details",
        action: CommandAction::Ui,
    },
];
